"""empty message

Revision ID: 62060e165c3a
Revises: dd25761f6350
Create Date: 2020-01-11 14:15:09.895764

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62060e165c3a'
down_revision = 'dd25761f6350'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blood_request',
    sa.Column('blood_req_id', sa.Integer(), nullable=False),
    sa.Column('blood_group_id', sa.Integer(), nullable=True),
    sa.Column('location', sa.String(length=256), nullable=True),
    sa.Column('person_name', sa.String(length=256), nullable=True),
    sa.Column('description', sa.String(length=1024), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['blood_group_id'], ['blood_group.blood_group_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('blood_req_id')
    )
    op.create_table('donation',
    sa.Column('donation_id', sa.Integer(), nullable=False),
    sa.Column('donor_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('request_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['donor_id'], ['user.user_id'], ),
    sa.ForeignKeyConstraint(['request_id'], ['blood_request.blood_req_id'], ),
    sa.PrimaryKeyConstraint('donation_id')
    )
    op.create_table('user',
    sa.Column('user_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('username', sa.String(length=256), nullable=True),
    sa.Column('email', sa.String(length=256), nullable=True),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.Column('blood_group_id', sa.Integer(), nullable=True),
    sa.Column('national_id', sa.String(length=20), nullable=True),
    sa.Column('last_donation_id', sa.Integer(), nullable=True),
    sa.Column('diseases', sa.String(length=1024), nullable=True),
    sa.Column('about', sa.String(length=1024), nullable=True),
    sa.Column('profile_pic', sa.TEXT(), nullable=True),
    sa.Column('profile_setup', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['blood_group_id'], ['blood_group.blood_group_id'], ),
    sa.ForeignKeyConstraint(['last_donation_id'], ['donation.donation_id'], ),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('user_login',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=1024), nullable=True),
    sa.Column('email', sa.String(length=256), nullable=True),
    sa.Column('password', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_login')
    op.drop_table('user')
    op.drop_table('donation')
    op.drop_table('blood_request')
    # ### end Alembic commands ###
