"""empty message

Revision ID: dd25761f6350
Revises: c625e0c24382
Create Date: 2020-01-11 14:12:50.274828

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd25761f6350'
down_revision = 'c625e0c24382'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('donation', 'donor_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('donation', 'donor_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
